# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_useri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='useris',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
