# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20170105_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='useris',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(related_name='users', to='users.Course'),
        ),
    ]
