# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-05 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0017_auto_20170105_1606'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.RemoveField(
            model_name='useri',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Useri',
        ),
    ]
