# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_course_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(related_name='xixi', to='users.User'),
        ),
    ]
