# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170106_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to='users.User'),
        ),
    ]
