# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_course_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Picture',
            new_name='picture',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Teacher',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Value',
            new_name='value',
        ),
    ]
